import { NextRequest, NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: NextRequest) {
  try {
    const { templateId, fieldValues, email } = await req.json();

    if (!templateId || !email) {
      return NextResponse.json({ error: 'Missing templateId or email' }, { status: 400 });
    }

    const supabase = createServiceClient();

    // Insert draft — token is generated by the DB default
    const { data, error } = await supabase
      .from('drafts')
      .insert({ template_id: templateId, field_values: fieldValues ?? {}, email })
      .select('token')
      .single();

    if (error) throw error;

    const token = data.token as string;
    const draftUrl = `${process.env.NEXT_PUBLIC_APP_URL ?? 'https://invitia.co'}/draft/${token}`;

    // Send email via Resend
    await resend.emails.send({
      from: 'Invitia <noreply@invitia.co>',
      to: email,
      subject: 'Your invitation draft is saved',
      html: `
        <div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;background:#09090b;color:#fff;border-radius:16px;padding:40px 32px;">
          <h1 style="font-size:24px;font-weight:700;margin:0 0 8px;color:#fff;">Your draft is ready</h1>
          <p style="color:rgba(255,255,255,0.6);margin:0 0 32px;font-size:15px;line-height:1.6;">
            We saved your invitation design. Click the button below to pick up where you left off.
            This link will expire in <strong style="color:#f0d060;">7 days</strong>.
          </p>
          <a href="${draftUrl}" style="display:inline-block;background:linear-gradient(135deg,#b8973a 0%,#f0d060 50%,#b8973a 100%);color:#1a1200;font-weight:700;font-size:15px;padding:14px 32px;border-radius:8px;text-decoration:none;">
            Continue Editing →
          </a>
          <p style="color:rgba(255,255,255,0.3);font-size:12px;margin:32px 0 0;">
            Or copy this link: ${draftUrl}
          </p>
        </div>
      `,
    });

    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error('[POST /api/drafts]', err);
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
